title: Assesment 1
author: Josh Misener
email: jmisener@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Hosting space for assesment 1

# social links
github_username:  jmisener9029

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
